### ISSUE TITLE
Feature Request - Check connection is needed for Apigee Infra

### ISSUE THREAD

**Issue by jashan05** [xebialabs-community/xld-apigee-plugin#17]
As of now there is no provision to check the connections from XLD server to Apigee Infra. Check connection would be a great help.

**Comment by ltutar** [comment]
Done. See https://github.com/xebialabs-community/xld-apigee-plugin/pull/18 and release v1.0.7

**Comment by jashan05** [comment]
Thanks Levant for Quick Fix.
