### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xld-apigee-plugin#22]
The plugin is sometimes giving the following error. Retrying the task solves it. Make it more robust.

Error while executing script [apigee/undeploy-and-remove-shared-flow.py]: requests.exceptions.SSLError: [Errno 1] Illegal state exception in <script> at line number 16
com.xebialabs.platform.script.jython.JythonException: Error while executing script [apigee/undeploy-and-remove-shared-flow.py]: requests.exceptions.SSLError: [Errno 1] Illegal state exception in <script> at line number 16
at com.xebialabs.platform.script.jython.JythonException$.apply(JythonException.scala:17)
at com.xebialabs.platform.script.jython.JythonSupport$$anonfun$executeScript$3.apply(JythonSupport.scala:45)

**Comment by ltutar** [comment]
https://stackoverflow.com/questions/36060505/ssl-illegal-state-exception-in-jython

I am using jython-standalone-2.7.0.jar

**Comment by hierynomus** [comment]
Which version of xld @ltutar ?

**Comment by ltutar** [comment]
XLD 7.0.1
also with XLR 7.0.2

**Comment by ltutar** [comment]
After using jython-standalone-2.7.1.patch2609.jar from xld version 7.5.0 with xld version 7.0.1, the error did not occur.

**Comment by ltutar** [comment]
use the new jython or migrate xld
