### ISSUE TITLE
Multiple revisions deployed for proxies with no virtual host

### ISSUE THREAD

**Issue by vpulagarwal** [xebialabs-community/xld-apigee-plugin#24]
Use Case: In Apigee we have are building some proxies with no virtual hosts in it. 
So the `default.xml` has a configuration below:

```xml
<HTTPProxyConnection>
        <BasePath>/v1/novhost</BasePath>
        <Properties/>
</HTTPProxyConnection>
```

Issue: Whenever you deploy an API proxy with such configuration the new revision is deployed but even after the successful deployment it does not undeploy the previous revision.

Possible solution: After successful deployment, check if there are any older revisions deployed. If yes, then undeploy the older revisions.

**Comment by ltutar** [comment]
See https://github.com/xebialabs-community/xld-apigee-plugin/releases/tag/v1.1.0

**Comment by ltutar** [comment]
Hi Vipul. Can you close this issue when you have time? Thanx.
